

export const FORMULARI_PROJECTE = 'FORMULARI_PROJECTE';
export const OBTENIR_PROJECTES = 'OBTENIR_PROJECTES';
export const AFEGIR_PROJECTE = 'AFEGIR_PROJECTE';
export const VALIDAR_FORMULARI = 'VALIDAR_FORMULARI';
export const PROJECTE_ACTUAL = 'PROJECTE_ACTUAL';
export const ELIMINAR_PROJECTE = 'ELIMINAR_PROJECTE';
export const PROJECTE_ERROR = 'PROJECTE_ERROR';

export const FEINES_PROJECTE = 'FEINES_PROJECTE';
export const AFEGIR_FEINA = 'AFEGIR_FEINA';
export const VALIDAR_FEINA = 'VALIDAR_FEINA';
export const ELIMINAR_FEINA = 'ELIMINAR_FEINA';

export const FEINA_ACTUAL = 'FEINA_ACTUAL';
export const ACTUALITZAR_FEINA = 'ACTUALITZAR_FEINA';
export const NETEJAR_FEINA = 'NETEJAR_FEINA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const AMAGAR_ALERTA = 'AMAGAR_ALERTA';

export const REGISTRE_CORRECTE = 'REGISTRE_CORRECTE';
export const REGISTRE_ERROR = 'REGISTRE_ERROR';
export const OBTENIR_USUARI = 'OBTENIR_USUARI';
export const LOGIN_CORRECTE = 'LOGIN_CORRECTE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const TANCAR_SESSIO = 'TANCAR_SESSIO';